Fix mozci scopes for Matrix notifs + Add 2 flags to monitoring hooks
mozilla/community-tc-config pull request #467
Opened 2022-02-22 14:41 UTC by EvaBardou

Related to https://github.com/mozilla/mozci/issues/647 and https://github.com/mozilla/mozci/issues/608

2022-02-22 14:56 UTC, marco-c approved these changes

2022-02-23 10:44 UTC, petemoore requested changes
It is close, but just needs a little tweaking. Thanks!

2022-02-23 10:44 UTC, petemoore commented on config/projects/mozci.yml
> +        - notify:matrix-room:!vNAdpBnFtfGfispLtR:mozilla.org
This middle line (68) is not needed - the internal room ID on line 69 (`!vNAdpBnFtfGfispLtR:mozilla.org`) is the correct way to refer to the `#sheriff-notifications` room.

However, I suspect the scope needed is probably `queue:route:notify.matrix-room.!vNAdpBnFtfGfispLtR:mozilla.org` unless the hook calls the notify API at runtime from the task. If it notifies the channel by including the task route `notify.matrix-room.!vNAdpBnFtfGfispLtR:mozilla.org` in the task definition, then `queue:route:notify.matrix-room.!vNAdpBnFtfGfispLtR:mozilla.org` is instead the required scope.

It would be nice to change the comment from `to code sheriffs through Matrix` to something like `to #sheriff-notifications room on Matrix` (just to be a bit more explicit).

Many thanks!

2022-02-23 10:54 UTC, La0 commented on config/projects/mozci.yml
> +        - notify:matrix-room:!vNAdpBnFtfGfispLtR:mozilla.org
We are using the notify API at runtime from the task. Here is an example of [currently failing task](https://community-tc.services.mozilla.com/tasks/ZAwPzeUNSkCbZg09eu8mfg/runs/0/logs/public/logs/live.log) which mention the internal Matrix room ID.

I think @EvaBardou added both values to match what is done on the [servo](https://github.com/mozilla/community-tc-config/blob/main/config/projects/servo.yml#L32) project

2022-02-23 11:02 UTC, EvaBardou commented on config/projects/mozci.yml
> +        - notify:matrix-room:!vNAdpBnFtfGfispLtR:mozilla.org
Thanks @La0 for your reply. :smile: 
@petemoore I updated the comment and deleted the unnecessary/erroneous scope from line 68.

2022-02-23 11:49 UTC, petemoore approved these changes
Looks great, many thanks!

2022-02-23 11:50 UTC, merged

2022-02-23 11:59 UTC, petemoore commented
Changes applied:

```
Updating Hook=project-mozci/monitoring-testing
Updating Role=hook-id:project-mozci/decision-task-production
Updating Hook=project-mozci/monitoring-production
Updating Role=hook-id:project-mozci/decision-task-testing
```